version: "3"
services:
  backend:
    image: prpa1984/fast_api_vae:latest
    #container_name: backend
    volumes:
      - ./fast_api:/src
    ports:
      - "8000:8000"

  frontend:
    image: prpa1984/streamlit:latest
    #container_name: frontend
    volumes:
      - ./streamlit:/src
    ports:
      - "8501:8501"

# docker compose automáticamente nos crea una red que conecta a los dos containers, 
# accediendo por su nombre como host