name: Docker build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build docker fast_api
      run: |
        cd fast_api
        docker build . --tag=prpa1984/fast_api_vae:latest
    - uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_LOGIN_USERNAME }}
        password: ${{ secrets.DOCKER_LOGIN_PASSWORD }}
    - name: Push the Docker image
      run: docker push prpa1984/fast_api_vae:latest
    - name: Build docker streamlit
      run: |
        cd streamlit
        docker build . --tag=prpa1984/streamlit:latest
    - name: Push the Docker image
      run: docker push prpa1984/streamlit:latest